//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace ConfigData
{
	public class ConfigDataManager
	{
		private Hashtable unitPropertiesMap = new Hashtable();

		public Hashtable UnitPropertiesMap {
			get {
				return unitPropertiesMap;
			}
		}

		private Hashtable skillInfoMap = new Hashtable();

		public Hashtable SkillInfoMap {
			get {
				return skillInfoMap;
			}
		}

		public static ConfigDataManager Singleton = new ConfigDataManager();
		public static bool Loaded = false;
		public ConfigDataManager ()
		{
		}
		public void Load(string path)
		{
			if (Loaded) 
			{
				return;			
			}

			{
				UnitProperties unitPropertiesConf = new UnitProperties();
				unitPropertiesConf.LoadFrom(path + "/Data/ConfigUnitProperties.csv");
				for (int i = 0; i < unitPropertiesConf.Count(); i++) 
				{
					DataUnitProperties test= unitPropertiesConf.Get(i);
					unitPropertiesMap.Add(test.id,test);
				}
			}

			{
				SkillInfo skillInfosConf = new SkillInfo();
				skillInfosConf.LoadFrom(path + "/Data/ConfigSkillInfo.csv");
				for (int i = 0; i < skillInfosConf.Count(); i++) 
				{
					DataSkillInfo test= skillInfosConf.Get(i);
					skillInfoMap.Add(test.id,test);
				}
			}
			Loaded = true;
		}
	}
}

