//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ConfigData;
using GameBase;
using UnityEngine;

namespace SkillSystem
{
	public class NormalAttack:Skill
	{
		public NormalAttack (UnitProperty unit,DataSkillInfo skillData):base(unit,skillData)
		{

		}

		public override bool CanUseSkill ()
		{
			Grid targetPos = GridsManager.Singleton.SceneGrids.GetGrid(owner.Pos.PosX,owner.Pos.PosY + 1);
			if(targetPos == null)
			{
				return false;
			}
			if(targetPos.Inner == null)
			{
				return false;
			}
			if(coolDown)
			{
				return false;
			}
			//and so on
			return true;
		}

		public override bool UseSkill ()
		{
			if(coolDown)
			{
				return false;
			}
			Grid targetPos = GridsManager.Singleton.SceneGrids.GetGrid(owner.Pos.PosX + 1,owner.Pos.PosY);

			if(targetPos == null)
			{
				return false;
			}

			UnitProperty target = targetPos.Inner;
			if(target == null)
			{
				return false;
			}
	
			coolDown = true;
			GameObject.FindWithTag("Main").GetComponent<TimerManager>().SetTimer(data.cool_down,HandleCoolDownFinished);
			//do action then call back do after
			int damage = Mathf.Min(owner.Atk - target.Def,target.Hp);
			target.Hp = target.Hp - damage;
			return true;
		}
	}
}

