//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ConfigData;
using GameBase;

namespace SkillSystem
{
	public class Skill
	{
		protected DataSkillInfo data;
		protected UnitProperty owner;
		protected bool coolDown = false;
		public Skill(UnitProperty unit,DataSkillInfo skillData)
		{
			owner = unit;
			data = skillData;
		}

		public virtual bool CanUseSkill()
		{
			return false;
		}

		public virtual bool UseSkill()
		{
			return false;
		}

		public void HandleCoolDownFinished()
		{
			coolDown = false;
		}
	}
}

