//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ConfigData;
using GameBase;

namespace SkillSystem
{
	public class SkillFactory
	{
		public static SkillFactory Singleton = new SkillFactory();
		public SkillFactory ()
		{
		}

		public Skill Create(UnitProperty unit,int id)
		{
			switch (id) 
			{
			case 1:
				return new NormalAttack(unit,(DataSkillInfo)ConfigDataManager.Singleton.SkillInfoMap[id]);
			default:
				break;
			}
			return null;
		}
	}
}

