//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace GameBase
{
	public class GridsManager
	{
		public static GridsManager Singleton = new GridsManager();
		private Grids sceneGrids;

		public Grids SceneGrids {
			get {
				return sceneGrids;
			}
		}

		public GridsManager ()
		{
		}

		public void CreateGrids(Rect rect,int x,int y)
		{
			sceneGrids = new Grids(rect,x,y);
		}
	}
}

