//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GameBase
{
	public class Grid
	{
		private int posX;

		public int PosX 
		{
			get 
			{
				return posX;
			}
		}

		private int posY;

		public int PosY 
		{
			get 
			{
				return posY;
			}
		}

		private Rect rect;
		private GameObject inner;

		public GameObject Inner 
		{
			get 
			{
				return inner;
			}
			set 
			{
				inner = value;
			}
		}

		public Rect Rect 
		{
			get 
			{
				return rect;
			}
		}

		public Grid()
		{
		}
		public Grid (int x,int y,Rect gridRect)
		{
			posX = x;
			posY = y;
			rect = gridRect;
		}
	}
}

