//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GameBase
{
	public class Grids
	{
		private int m_nX = 9;
		private int m_nY = 5;
		private Rect m_rect;
		private Vector2 cellSize;

		public Grids ()
		{
		}

		public Grids(Rect rect,int nX,int nY)
		{
			m_nX = nX;
			m_nY = nY;
			m_rect = rect;
			cellSize.x = rect.width / nX;
			cellSize.y = rect.height / nY;
		}

		public Rect GetGrid(int nX,int nY)
		{
			if (nX >= m_nX || nX < 0 || nY >= m_nY || nY < 0) 
			{
				return new Rect();
			}
			return new Rect (m_rect.x + cellSize.x * nX, m_rect.y + cellSize.y * nY, cellSize.x, cellSize.y);
		}

		public Rect GetGrid(Vector2 pos)
		{
			int nX = GetXIndex(pos.x);
			int nY = GetYIndex(pos.y);
			return GetGrid (nX, nY);
		}

		public int GetXIndex(float fX)
		{
			return (int)((fX-m_rect.x) / cellSize.x);
		}

		public int GetYIndex(float fY)
		{
			return (int)((fY-m_rect.y) / cellSize.y);
		}
	}
}
