//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace GameBase
{
	public class TimerWrapper : IComparable
	{
		public TimerWrapper (Timer timer,int nMaxTickCount,float fTick)
		{
			m_timer = timer;
			m_nTickCount = (int)(timer.m_fTime/fTick);
			m_nGroupCount = m_nTickCount/nMaxTickCount;
		}
		#region IComparable Members
		public int CompareTo(object obj)
		{
			TimerWrapper wrapper = obj as TimerWrapper;
			if(m_nTickCount > wrapper.m_nTickCount)
			{
				return 1;
			}
			else if(m_nTickCount < wrapper.m_nTickCount)
			{
				return -1;
			}
			return 0;

		}	
		#endregion
		public int m_nTickCount;
		public int m_nGroupCount;
		public Timer m_timer;
	}
}

