//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace GameBase
{
	public class Timer:IComparable
	{
		public delegate void OnTimeHandle();
		public event OnTimeHandle timerEvent;
		private float absTime;
		public Timer (float time,OnTimeHandle newEvent)
		{
			timerEvent += newEvent;
			absTime = time;
		}

		public virtual bool OnTime()
		{
			if (timerEvent != null) 
			{
				timerEvent();
			}
			return false;
		}

		public void Stop()
		{
			timerEvent = null;
		}
		public int CompareTo (object obj)
		{
			if (absTime > ((Timer)obj).absTime) 
			{
				return 1;
			}
			else if (absTime < ((Timer)obj).absTime)
			{
				return -1;
			}
			return 0;
			
		}
	}
}

